export default {
  gender: ["female", "male"],
  color: [
    "8-bit",
    "Baby",
    "Biscuit",
    "Blue",
    "Brown",
    "Burlap",
    "Camouflage",
    "Candy",
    "Checkered",
    "Chocolate",
    "Christmas",
    "Clay",
    "Cloud",
    "Custard",
    "Darigan",
    "Desert",
    "Dimensional",
    "Disco",
    "Elderly",
    "Electric",
    "Eventide",
    "Faerie",
    "Fire",
    "Ghost",
    "Glowing",
    "Gold",
    "Green",
    "Grey",
    "Halloween",
    "Ice",
    "Island",
    "Jelly",
    "Magma",
    "Maractite",
    "Maraquan",
    "Marble",
    "Mosaic",
    "Mutant",
    "Oil Paint",
    "Orange",
    "Origami",
    "Pastel",
    "Pink",
    "Pirate",
    "Plushie",
    "Polka Dot",
    "Purple",
    "Rainbow",
    "Red",
    "Relic",
    "Robot",
    "Royal",
    "Shadow",
    "Silver",
    "Sketch",
    "Skunk",
    "Snot",
    "Snow",
    "Speckled",
    "Split",
    "Sponge",
    "Spotted",
    "Starry",
    "Stealthy",
    "Strawberry",
    "Steampunk",
    "Striped",
    "Swamp gas",
    "Toy",
    "Transparent",
    "Tyrannian",
    "Water",
    "White",
    "Woodland",
    "Wraith",
    "Yellow",
    "Zombie"
  ],
  breed: [
    "Acara",
    " Aisha",
    "Blumaroo",
    "Bori",
    "Bruce",
    "Buzz",
    "Chia",
    "Chomby",
    "Cybunny",
    "Draik",
    "Elephante",
    "Eyrie",
    "Flotsam",
    "Gelert",
    "Gnorbu",
    "Grarrl",
    "Grundo",
    "Hissi",
    "Ixi",
    "Jetsam",
    "Jubjub",
    "Kacheek",
    "Kau",
    "Kiko",
    "Koi",
    "Korbat",
    "Kougra",
    "Krawk",
    "Kyrii",
    "Lenny",
    "Lupe",
    "Lutari",
    "Meerca",
    "Moehog",
    "Mynci",
    "Nimmo",
    "Ogrin",
    "Peophin",
    "Poogle",
    "Pteri",
    "Quiggle",
    "Ruki",
    "Scorchio",
    "Shoyru",
    "Skeith",
    "Techo",
    "Tonu",
    "Tuskaninny",
    "Uni",
    "Usul",
    "Vandagyre",
    "Wocky",
    "Xweetok",
    "Yurble",
    "Zafara"
  ],
  world: [
    "Altador",
    "Brightvale",
    "Darigan Citadel",
    "Faerieland",
    "the Haunted Woods",
    "Kiko Lake",
    "Krawk Island",
    "Kreludor",
    "Lutari Island",
    "Maraqua",
    "Meridell",
    "Moltara",
    "Mystery Island",
    "Roo Island",
    "Shenkuu",
    "Terror Mountain",
    "the Lost Desert",
    "Tyrannia",
    "the Virtupets Space Station"
  ],
  origin: [
    "poet",
    "champion",
    "hero",
    "farmer",
    "traveler",
    "merchant",
    "mercenary",
    "sailor",
    "soldier",
    "wanderer",
    "child",
    "necromancer",
    "hermit",
    "boatman",
    "gambler",
    "dancer",
    "acrobat",
    "outlaw",
    "philanthropist",
    "bandit",
    "model",
    "bounty hunter",
    "maid",
    "teacher",
    "philosopher",
    "comedian",
    "law enforcer",
    "gardener",
    "baker",
    "squire",
    "musician",
    "actor",
    "martial artist",
    "fashion designer",
    "singer",
    "thief",
    "shopkeeper",
    "advisor",
    "villain",
    "sidekick",
    "gypsy",
    "scientist",
    "referee",
    "grave robber",
    "magician",
    "spy",
    "scribe",
    "cartographer",
    "fortune-teller",
    "explorer",
    "superhero",
    "wizard",
    "occultist",
    "gladiator",
    "treasure-hunter",
    "rebel",
    "barbarian",
    "beastmaster",
    "photographer",
    "warrior",
    "bard",
    "smuggler",
    "student",
    "media personality",
    "reporter",
    "architect",
    "bookworm",
    "beggar",
    "fire fighter",
    "chef",
    "pilot",
    "inventor",
    "hacker",
    "yooyuball player",
    "librarian",
    "gourmand",
    "physicist",
    "astronomer",
    "pirate",
    "juggler",
    "trader",
    "hiker",
    "first mate",
    "writer",
    "minion",
    "janitor",
    "socialite",
    "nurse",
    "doctor",
    "bookkeeper",
    "servant",
    "romantic",
    "apprentice",
    "tourist",
    "tailor",
    "navigator",
    "painter",
    "artist",
    "linguist",
    "card shark"
  ]
};
